module.exports = {
  index_html: '<!DOCTYPE html><html><head><title>MultiVision</title><link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/vendor/toastr/toastr.css"><link rel="stylesheet" href="/css/site.css"></head><body ng-app="app"><div class="navbar navbar-inverse navbar-fixed-top"><div class="container"><div class="navbar-header"><a href="/" class="navbar-brand">MultiVision<h6>-Extreme Tech Training</h6></a></div><div class="navbar-collapse collapse"><ul class="nav navbar-nav"><li><a href="/">Home</a></li><li><a href="/courses">Courses</a></li></ul><div ng-include="\'/partials/account/navbar-login\'"></div></div></div></div><section class="content"><div ng-view></div></section><footer class="container text-center"><p>&copy; 2013 MultiVision Corp International Ltd.</p></footer><script type="text/javascript" src="/vendor/jquery/jquery.js"></script><script type="text/javascript" src="/vendor/bootstrap/dist/js/bootstrap.js"></script><script type="text/javascript" src="/vendor/toastr/toastr.js"></script><script type="text/javascript" src="/vendor/angular/angular.js"></script><script type="text/javascript" src="/vendor/angular-resource/angular-resource.js"></script><script type="text/javascript" src="/vendor/angular-route/angular-route.js"></script><script type="text/javascript" src="/app/app.js"></script><script type="text/javascript" src="/app/main/mvMainCtrl.js"></script><script type="text/javascript" src="/app/account/mvNavBarLoginCtrl.js"></script><script type="text/javascript" src="/app/account/mvIdentity.js"></script><script type="text/javascript" src="/app/common/mvNotifier.js"></script><script type="text/javascript" src="/app/account/mvAuth.js"></script><script type="text/javascript" src="/app/account/mvUser.js"></script><script type="text/javascript" src="/app/account/mvSignupCtrl.js"></script><script type="text/javascript" src="/app/account/mvProfileCtrl.js"></script><script type="text/javascript" src="/app/admin/mvUserListCtrl.js"></script><script type="text/javascript" src="/app/courses/mvCourseListCtrl.js"></script><script type="text/javascript" src="/app/courses/mvCourse.js"></script></body></html>'
, courses_json: [ { _id: '554fcbaad933f5154a40a8fd',
    title: 'C# for Sociopaths',
    featured: true,
    published: '2013-10-05T06:00:00.000Z',
    __v: 0,
    tags: [ 'C#' ] },
  { _id: '554fcbaad933f5154a40a8ff',
    title: 'Super Duper Expert C#',
    featured: false,
    published: '2013-10-01T06:00:00.000Z',
    __v: 0,
    tags: [ 'C#' ] },
  { _id: '554fcbaad933f5154a40a900',
    title: 'Visual Basic for Visual Basic Developers',
    featured: false,
    published: '2013-07-12T06:00:00.000Z',
    __v: 0,
    tags: [ 'VB' ] },
  { _id: '554fcbaad933f5154a40a901',
    title: 'Pedantic C++',
    featured: true,
    published: '2013-01-01T07:00:00.000Z',
    __v: 0,
    tags: [ 'C++' ] },
  { _id: '554fcbaad933f5154a40a904',
    title: 'A Survival Guide to Code Reviews',
    featured: true,
    published: '2013-02-01T07:00:00.000Z',
    __v: 0,
    tags: [ 'Coding' ] },
  { _id: '554fcbaad933f5154a40a905',
    title: 'How to Job Hunt Without Alerting your Boss',
    featured: true,
    published: '2013-10-07T06:00:00.000Z',
    __v: 0,
    tags: [ 'Misc' ] },
  { _id: '554fcbaad933f5154a40a902',
    title: 'JavaScript for People over 20',
    featured: true,
    published: '2013-10-13T06:00:00.000Z',
    __v: 0,
    tags: [ 'JS' ] },
  { _id: '554fcbaad933f5154a40a906',
    title: 'How to Keep your Soul and go into Management',
    featured: false,
    published: '2013-08-01T06:00:00.000Z',
    __v: 0,
    tags: [ 'Management' ] },
  { _id: '554fcbaad933f5154a40a909',
    title: 'Code Reviews for Jerks',
    featured: false,
    published: '2013-10-01T06:00:00.000Z',
    __v: 0,
    tags: [ 'Coding' ] },
  { _id: '554fcbaad933f5154a40a90a',
    title: 'How to Deal with Narcissistic Coworkers',
    featured: true,
    published: '2013-02-15T07:00:00.000Z',
    __v: 0,
    tags: [ 'Misc' ] },
  { _id: '554fcbaad933f5154a40a8fe',
    title: 'C# for Non-Sociopaths',
    featured: true,
    published: '2013-10-12T06:00:00.000Z',
    __v: 0,
    tags: [ 'C#' ] },
  { _id: '554fcbaad933f5154a40a907',
    title: 'Telling Recruiters to Leave You Alone',
    featured: false,
    published: '2013-11-01T06:00:00.000Z',
    __v: 0,
    tags: [ 'Misc' ] },
  { _id: '554fcbaad933f5154a40a90b',
    title: 'Death March Coding for Fun and Profit',
    featured: true,
    published: '2013-07-01T06:00:00.000Z',
    __v: 0,
    tags: [ 'Coding', 'Misc' ] },
  { _id: '554fcbaad933f5154a40a903',
    title: 'Maintainable Code for Cowards',
    featured: true,
    published: '2013-03-01T07:00:00.000Z',
    __v: 0,
    tags: [ 'Coding' ] },
  { _id: '554fcbaad933f5154a40a908',
    title: 'Writing Code that Doesn\'t Suck',
    featured: true,
    published: '2013-10-13T06:00:00.000Z',
    __v: 0,
    tags: [ 'Coding' ] } ]
};